In [84]:
import torch
from torch import nn
import numpy as np

Creo un tensore 8x8 che corrisponde all'immagine di prova, le due righe commentate sono per creare un tensore con valori random 0 e 1

In [85]:
#array=np.random.randint(0,2,size=(8,8)).astype(np.float32)
#tensor=torch.from_numpy(array)
tensor=torch.tensor([[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],[1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0],[1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0],[1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0],
                    [0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0],[0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0],[0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0],[1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0]])
print(tensor)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 1., 0., 1., 0.],
        [1., 1., 0., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 1., 1., 1., 1.],
        [0., 1., 0., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 0., 1., 1., 0., 0., 1., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0.]])


Creo un tensore 3x3 che corrisponde al kernel. La variabile count serve a contare il numero di bit a 1 nel kernel

In [86]:
kernel=torch.tensor([[1.0,1.0,-1.0],[1.0,1.0,1.0],[-1.0,1.0,-1.0]])
count=0
for item in kernel.flatten():
  if item==1:
    count=count+1
kernel

tensor([[ 1.,  1., -1.],
        [ 1.,  1.,  1.],
        [-1.,  1., -1.]])

Creo una rete neurale convolutiva

In [87]:
net=nn.Conv2d(1,1,3,padding='valid',bias=False)
print(net)

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=valid, bias=False)


Imposto manualmente i pesi della rete utilizzando il kernel creato da me

In [88]:
with torch.no_grad():
  net.weight.copy_(kernel.unsqueeze(0).unsqueeze(0))

Estendo il tensore dell'immagine in modo da essere passato in input alla rete convolutiva

In [89]:
img_input = tensor.unsqueeze(0).unsqueeze(0)
output=net(img_input)

In [90]:
print(output.squeeze())

tensor([[ 4.,  1.,  4.,  1.,  3.,  2.],
        [ 2.,  4., -1.,  2., -1.,  0.],
        [ 6.,  1.,  2.,  4.,  1.,  4.],
        [ 3.,  1.,  2., -1.,  4.,  0.],
        [ 1.,  3.,  0.,  2.,  0.,  3.],
        [ 1.,  2.,  2.,  2.,  1.,  2.]], grad_fn=<SqueezeBackward0>)


Istanzio un tensore detection che asserisce "1" quando nota una sottomatrice compatibile con il kernel (0 altrimenti)

In [91]:
detection=(output.squeeze()==count).float()
print(detection)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
