In [50]:
import torch
from torch import nn
import numpy as np

In [51]:
#array=np.random.randint(0,2,size=(8,8)).astype(np.float32)
#tensor=torch.from_numpy(array)
tensor=torch.tensor([[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],[1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0],[1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0],[1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0],
                    [0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0],[0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0],[0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0],[1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0]])
print(tensor)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 1., 0., 1., 0.],
        [1., 1., 0., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 1., 1., 1., 1.],
        [0., 1., 0., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 0., 1., 1., 0., 0., 1., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0.]])


In [52]:
kernel=torch.tensor([[1.0,1.0,-1.0],[1.0,1.0,1.0],[-1.0,1.0,-1.0]])
count=0
for item in kernel.flatten():
  if item==1:
    count=count+1
kernel

tensor([[ 1.,  1., -1.],
        [ 1.,  1.,  1.],
        [-1.,  1., -1.]])

In [53]:
net=nn.Conv2d(1,1,3,padding='valid',bias=False)
print(net)

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=valid, bias=False)


In [54]:
with torch.no_grad():
  net.weight.copy_(kernel.unsqueeze(0).unsqueeze(0))

In [55]:
img_input = tensor.unsqueeze(0).unsqueeze(0)
output=net(img_input)
print(output.shape)

torch.Size([1, 1, 6, 6])


In [56]:
print(output.squeeze())

tensor([[ 4.,  1.,  4.,  1.,  3.,  2.],
        [ 2.,  4., -1.,  2., -1.,  0.],
        [ 6.,  1.,  2.,  4.,  1.,  4.],
        [ 3.,  1.,  2., -1.,  4.,  0.],
        [ 1.,  3.,  0.,  2.,  0.,  3.],
        [ 1.,  2.,  2.,  2.,  1.,  2.]], grad_fn=<SqueezeBackward0>)


In [57]:
detection=(output.squeeze()==count).float()
print(detection)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
